import{r as e,e as p,q as r,n as y,a as L,s as d,c as M,f as u,b as x,h as w,d as T,g as C,i as H}from"./assets/modals-listeners-Cc_Pxr9j.js";import"./assets/vendor-BUg1UuD4.js";function g(t,a,n,s){t.innerHTML="";const m=2,i=2;function c(o){const l=document.createElement("button");return l.classList.add("page-number"),l.textContent=o,o===a&&(l.disabled=!0,l.classList.add("active")),l.addEventListener("click",s),l}const v=Math.max(1,a-m),P=Math.min(n,a+i);for(let o=v;o<=P;o++)t.appendChild(c(o))}async function f(t){const a=t.target.textContent;r.page=Number(a),r.limit=window.innerWidth>=768?10:8,e.exercisePageWrapper.innerHTML="",e.exercises.innerHTML="";try{e.exercises.innerHTML='<div class="loader"></div>';const n=await p.getExercisesWithParams(r);if(r.maxPage=n.totalPages,e.exercises.innerHTML=L(n.results),r.maxPage===1)return;g(e.exercisePageWrapper,r.page,r.maxPage,f)}catch{d("Failed to load exercises. Please try again later.")}}async function E(t){t.preventDefault();const a=t.currentTarget,n=a.elements.query.value.trim();e.exercisePageWrapper.innerHTML="",e.exercises.innerHTML="",r.page=1,r.limit=window.innerWidth>=768?10:8,r.keyword=n;try{e.exercises.innerHTML='<div class="loader"></div>';const s=await p.getExercisesWithParams(r);if(r.maxPage=s.totalPages,s.results.length===0){e.exercises.innerHTML=`<p class="exercise-title-text">${y}</p>`;return}if(e.exercises.innerHTML=L(s.results),r.maxPage===1)return;g(e.exercisePageWrapper,r.page,r.maxPage,f)}catch{d("Failed to load exercises. Please try again later.")}finally{a.reset()}}async function F(t){if(t.preventDefault(),t.target!==t.currentTarget){e.exercises.innerHTML="",e.exercisePageWrapper.innerHTML="",e.searchForm.classList.add("active-search-form"),e.cardContainer.classList.add("hidden"),e.exerciseContainer.classList.remove("hidden"),r.page=1,r.keyword="",r.limit=window.innerWidth>=768?10:8,r.category_name=t.target.querySelector(".category-name").textContent,r.category_type=M[t.target.querySelector(".category-type").textContent.replace(/\s/g,"")],e.exercisesHeader.innerHTML=`Exercises / <span class="exercise-header-category">${r.category_name}</span>`,r.category_name=r.category_name.toLowerCase();try{e.exercises.innerHTML='<div class="loader"></div>';const a=await p.getExercisesWithParams(r);if(r.maxPage=a.totalPages,a.results.length===0){e.exercises.innerHTML=`<p class="exercise-title-text">${y}</p>`;return}if(e.exercises.innerHTML=L(a.results),r.maxPage===1)return;g(e.exercisePageWrapper,r.page,r.maxPage,f)}catch{d("Failed to load exercises. Please try again later.")}}}async function h(t=1){e.categories.innerHTML='<div class="loader categories-loader"></div>';const a=u.getFilterQuery(),n=window.innerWidth<768?9:12;try{const s=await u.fetchFilteredData(a,n,t),m=s.results.sort((i,c)=>i.name.localeCompare(c.name));e.categories.innerHTML="",m.forEach(i=>{const c=document.createElement("div");c.className="category-card",c.innerHTML=`
        <img
          src="${i.imgURL}"
          srcset="${i.imgURL} 1x, ${i.imgURL} 2x"
          alt="${i.name} exercise"
        />
        <div class="category-name">${i.name.charAt(0).toUpperCase()+i.name.slice(1)}</div>
        <div class="category-type">${i.filter}</div>
      `,e.categories.appendChild(c)}),e.categoriesWrap.innerHTML="",s.totalPages>1&&g(e.categoriesWrap,t,s.totalPages,b)}catch{d("Failed to load exercise categories. Please try again later.")}}function b(t){const a=Number(t.target.textContent);h(a)}function k(t){e.filterBtns.forEach(a=>{a.classList.remove("active-filter-btn")}),t.target.nodeName==="BUTTON"&&(t.target.classList.add("active-filter-btn"),e.searchForm.classList.remove("active-search-form"),e.cardContainer.classList.remove("hidden"),e.exerciseContainer.classList.add("hidden"),e.exercisesHeader.innerHTML="Exercises",u.setFilterQuery(t.target.textContent.trim()),h())}async function W(t){t.preventDefault(),x.getFormData(),x.verifyData()&&x.postEmail()}function R(){const t=new Date().getFullYear();e.footerYear.textContent=`@${t}`}function $(){window.addEventListener("scroll",()=>{window.scrollY>350?e.scrollUp.style.display="block":e.scrollUp.style.display="none"}),e.scrollUp.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})})}h();window.quoteRendered||(w(),window.quoteRendered=!0);e.searchForm.addEventListener("submit",E);e.filterBtnsList.addEventListener("click",k);e.footerForm.addEventListener("submit",W);e.categories.addEventListener("click",F);R();document.addEventListener("DOMContentLoaded",()=>{T(),C(),H()});$();document.addEventListener("keydown",t=>{t.key==="Escape"&&(e.exerciseModal.classList.contains("is-open")&&e.exerciseModal.classList.remove("is-open"),e.giveRatingModal.classList.contains("is-open")&&(e.giveRatingModal.classList.remove("is-open"),e.exerciseModal.classList.add("is-open")))});
//# sourceMappingURL=index.js.map
