import{r as e,e as u,q as a,n as y,a as L,s as d,c as M,f as p,b as x,h as T,d as C,g as w,i as H}from"./assets/modals-listeners-DmcGHMQV.js";import"./assets/vendor-BUg1UuD4.js";function g(t,r,n,s){t.innerHTML="";const m=2,i=2;function c(o){const l=document.createElement("button");return l.classList.add("page-number"),l.textContent=o,o===r&&(l.disabled=!0,l.classList.add("active")),l.addEventListener("click",s),l}const v=Math.max(1,r-m),P=Math.min(n,r+i);for(let o=v;o<=P;o++)t.appendChild(c(o))}async function f(t){const r=t.target.textContent;a.page=Number(r),a.limit=window.innerWidth>=768?10:8,e.exercisePageWrapper.innerHTML="",e.exercises.innerHTML="";try{e.exercises.innerHTML='<div class="loader"></div>';const n=await u.getExercisesWithParams(a);if(a.maxPage=n.totalPages,e.exercises.innerHTML=L(n.results),a.maxPage===1)return;g(e.exercisePageWrapper,a.page,a.maxPage,f)}catch{d("Failed to load exercises. Please try again later.")}}async function E(t){t.preventDefault();const r=t.currentTarget,n=r.elements.query.value.trim();e.exercisePageWrapper.innerHTML="",e.exercises.innerHTML="",a.page=1,a.limit=window.innerWidth>=768?10:8,a.keyword=n;try{e.exercises.innerHTML='<div class="loader"></div>';const s=await u.getExercisesWithParams(a);if(a.maxPage=s.totalPages,s.results.length===0){e.exercises.innerHTML=`<p class="exercise-title-text">${y}</p>`;return}if(e.exercises.innerHTML=L(s.results),a.maxPage===1)return;g(e.exercisePageWrapper,a.page,a.maxPage,f)}catch{d("Failed to load exercises. Please try again later.")}finally{r.reset()}}async function F(t){if(t.preventDefault(),t.target!==t.currentTarget){e.exercises.innerHTML="",e.exercisePageWrapper.innerHTML="",e.searchForm.classList.add("active-search-form"),e.cardContainer.classList.add("hidden"),e.exerciseContainer.classList.remove("hidden"),a.page=1,a.keyword="",a.limit=window.innerWidth>=768?10:8,a.category_name=t.target.querySelector(".category-name").textContent,a.category_type=M[t.target.querySelector(".category-type").textContent.replace(/\s/g,"")],e.exercisesHeader.innerHTML=`Exercises / <span class="exercise-header-category">${a.category_name}</span>`,a.category_name=a.category_name.toLowerCase();try{e.exercises.innerHTML='<div class="loader"></div>';const r=await u.getExercisesWithParams(a);if(a.maxPage=r.totalPages,r.results.length===0){e.exercises.innerHTML=`<p class="exercise-title-text">${y}</p>`;return}if(e.exercises.innerHTML=L(r.results),a.maxPage===1)return;g(e.exercisePageWrapper,a.page,a.maxPage,f)}catch{d("Failed to load exercises. Please try again later.")}}}async function h(t=1){e.categories.innerHTML='<div class="loader categories-loader"></div>';const r=p.getFilterQuery(),n=window.innerWidth<768?9:12;try{const s=await p.fetchFilteredData(r,n,t),m=s.results.sort((i,c)=>i.name.localeCompare(c.name));e.categories.innerHTML="",m.forEach(i=>{const c=document.createElement("div");c.className="category-card",c.innerHTML=`
        <img
          src="${i.imgURL}"
          srcset="${i.imgURL} 1x, ${i.imgURL} 2x"
          alt="${i.name} exercise"
        />
        <div class="category-name">${i.name.charAt(0).toUpperCase()+i.name.slice(1)}</div>
        <div class="category-type">${i.filter}</div>
      `,e.categories.appendChild(c)}),e.categoriesWrap.innerHTML="",s.totalPages>1&&g(e.categoriesWrap,t,s.totalPages,b)}catch{d("Failed to load exercise categories. Please try again later.")}}function b(t){const r=Number(t.target.textContent);h(r)}function k(t){e.filterBtns.forEach(r=>{r.classList.remove("active-filter-btn")}),t.target.nodeName==="BUTTON"&&(t.target.classList.add("active-filter-btn"),e.searchForm.classList.remove("active-search-form"),e.cardContainer.classList.remove("hidden"),e.exerciseContainer.classList.add("hidden"),e.exercisesHeader.innerHTML="Exercises",p.setFilterQuery(t.target.textContent.trim()),h())}async function W(t){t.preventDefault(),x.getFormData(),x.verifyData()&&x.postEmail()}function $(){const t=new Date().getFullYear();e.footerYear.textContent=`@${t}`}function R(){window.addEventListener("scroll",()=>{window.scrollY>350?e.scrollUp.style.display="block":e.scrollUp.style.display="none"}),e.scrollUp.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})})}h();T();e.searchForm.addEventListener("submit",E);e.filterBtnsList.addEventListener("click",k);e.footerForm.addEventListener("submit",W);e.categories.addEventListener("click",F);$();document.addEventListener("DOMContentLoaded",()=>{C(),w(),H()});R();document.addEventListener("keydown",t=>{t.key==="Escape"&&(e.exerciseModal.classList.contains("is-open")&&e.exerciseModal.classList.remove("is-open"),e.giveRatingModal.classList.contains("is-open")&&(e.giveRatingModal.classList.remove("is-open"),e.exerciseModal.classList.add("is-open")))});
//# sourceMappingURL=index.js.map
